apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=${{ values.name }}'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-demo-gh/${{ values.name }}
spec:
  type: website
  {% if variable %}
  system: ${{ values.system }}
  {% endif %}
  lifecycle: dev
  owner: ${{ values.owner }}
